### PR TITLE
Standalone HTTP example with WebSockets

### PR DESCRIPTION
**Pull request by Elektrik1**

### CODE REVIEW

**Comment by sj-louw** [comment]
@Elektrik1 This is really good work. Very useful to have a Web frontend. Great Job!

**Comment by Elektrik1** [comment]
@sj-louw Thank you very much. HTML is being create as an framework (recently created DSC font with vectorial icons of PK5501 panel), hope other devs having different panels could provide their representation. A lot of changes ahead (beep tones, alarm memory preview in PK5501 style and etc).

**Comment by l33d** [comment]
Cool man, maybe i try. Is this a password for this website?

**Comment by Elektrik1** [comment]
@l33d Currently without password (just enter your WIFI credentials and make sure WIFI is not accessible for others).

**Comment by l33d** [comment]
Hi,

I try yesterday but have problem. I instal sketch on esp, add index.html to my server ( add ip inside from esp) but didn`t work. Maybe try tomorrow, where is the problem.

**Comment by Elektrik1** [comment]
I will write documentation soon on how to install. /data folders goes to ESP8266 SPIFFS partition, it should be uploaded after sketch upload via "ESP8266 Sketch Data Upload" button, which is available when ESP8266 Sketch upload tool is installed (https://github.com/esp8266/arduino-esp8266fs-plugin). The only thing you should enter is wifi SSID and PASSWORD to connect to AP. You don't need any external server, ESP is the server itself.
4M (1M spiffs) should be selected as flash size.

**Comment by l33d** [comment]
Thanks for reply, i try it in few days.

**Comment by PascalSI** [comment]
Hello, I tried to compile the version with HTTP, but i can not get ... Can you explain how to do this?

**Comment by taligentx** [comment]
Thanks @Elektrik1!  This is an excellent capability - merged into master to prepare for the next release.  If you have documentation on usage, it'd be useful to add it to the .ino sketch directly.

**Pull request merged**
