### PR TITLE
- add ESPHOME example

### PR DESCRIPTION
**Pull request by Dilbert66**
- Added esphome example with all statuses, services and arm/disarm functions

### CODE REVIEW

**Comment by carldebilly** [comment]
@taligentx Any hope this could be merged soon?

**Comment by taligentx** [comment]
I'll see if there's a clean way to merge by perhaps putting the files in the `extras` directory, I need to dig into esphome a bit to see how custom modules are typically distributed.  The `examples` folder is specifically used by the Arduino IDE and PlatformIO for sketches that can be selected, compiled, and uploaded and this esphome module wouldn't work in that context.

@carldebilly Check out https://github.com/Dilbert66/esphome-dsckeybus - Alain has a forked version of this library included as part of the project and has added several features to the fork.  In the future it may be possible for him to add this repo as a submodule but at the moment there are quite a few code changes that I need to implement before that would make sense.

**Comment by Dilbert66** [comment]
The custom part is the files dscalarm.yaml and dscalarm.h.  Installation not much different really than for example the Blynk virtual keyboard app where you have to first download a pile of libraries before you can compile it.  In this case you install your the dscalarm.yaml and dscalarm.h in your main esphome directory then create a subdirectory for the keybusinterface library and copy this library code there. You will need to adjust the include directive in the yaml to point to the correct paths of course.

**Comment by taligentx** [comment]
Merged, thanks!  I've placed this in `extras` so Arduino IDE, etc don't get tripped up, and will update README.md.

**Pull request merged**
