### PR TITLE
Added sanity checks and configs for systems with systems with 32 zones maximum support

### PR DESCRIPTION
**Pull request by Dilbert66**
Tested with my older PC5010 panel which has the smaller 05/11 cmds and only 32zone support . Used a config and some code that looks at the lenght of the 05 command and adjusts accordingly  Code works ok for zones. It does support zones in groups of 8.    Trying to use more than 32 zones will be ignored.  

Still more testing needed though for smaller systems.

### CODE REVIEW

**Comment by Dilbert66** [comment]
Ok, I think this should do it for now.  I realized my home panel was a version 2.0 and handles the zone expander ranges as groups of 4 zones compared to my other test system with version 4.6 which has support for 64 zones with 8 zone groups. Yes, I do plan on installing the new panel but need a new lcd keypad first.   The existing keypad will not work with the new panel.
Anyhow, to support the older versions. You need to set. dsc.panelVersion=2 and set maxZones=32.    Adding zone groups works the same way for  both versions.  You add them in groups of 8 (device address 9,10,11)  and the firmware will take care of the back end splitting if needed.

**Comment by Dilbert66** [comment]
I tried to find a way to identify the panel version using the cmd data but no luck so far.  Has to be there since the real zone expansion module can identify it and provide it's response accordingly.  Would be handy to automate the processing without the requirment for a config setting.

**Comment by Dilbert66** [comment]
I wonder if the size of the 0x11 command is a differentiator? With the version 2.0 it's it's 7 bytes (including stop bit)
With version 4.6 of my pc1864 it's  9.  That could be useful.  You did mention that earlier I remember.  Do all 3.x and above now use the 9 byte 0x11? Needs more logs.

**Comment by taligentx** [comment]
Excellent, thanks for the PR as always!

> I wonder if the size of the 0x11 command is a differentiator? 

As far as I've seen, there are two sets of Keybus command lengths so it should be straightforward to differentiate based on the size of 0x05 or 0x11.  I should probably add something like `uint8_t keybusVersion` to help with managing these variants.

**Comment by Dilbert66** [comment]
That's what I ended up doing.  In the panel handler , I added the check for the 05 cmd length and use that to set up the correct values for the cmd responses and handling. It seems to work ok so far. This is assuming of course that only the later versions 3+ started using the longer 05/11 cmd lengths.

**Pull request merged**
